export { ReactComponent as LogoIcon } from './logo.svg'
export { ReactComponent as HighlighterIcon } from './highlighter.svg'
export { ReactComponent as ReactIcon } from './react.svg'
export { ReactComponent as NodeJSIcon } from './nodeJS.svg'
export { ReactComponent as GitIcon } from './git.svg'
